# Generated by Django 4.2.5 on 2023-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_simulation_delete_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='x',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simulation',
            name='y',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
