# Generated by Django 4.2.5 on 2023-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_alter_simulation_graphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='graphic',
        ),
        migrations.AddField(
            model_name='simulation',
            name='graphic_urls',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
