# Generated by Django 4.2.5 on 2023-10-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0010_remove_simulation_x_remove_simulation_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsorptionFuelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absorption_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChaleurSpecFeulBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaleur_spec_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_surface', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DensiteFuelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densite_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiametreFuelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametre_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissiviteFuelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissivite_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FractionVolumiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction_volumiq', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HauteurFlamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hauteur_flamme', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HauteurFuelBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hauteur_fuel_bed', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimiteInitialOX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_initial_ox', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_spec', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeneurEnEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teneur_en_eau', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCombustion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_combustion', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='X1veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1veg', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='X2veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x2veg', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Y1veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y1veg', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Y2veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y2veg', models.FloatField(default=0.0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='abscisse_du_point_d_enregistrement',
            new_name='conductiviteBraise',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='chaleur_spécifique_du_combustible',
            new_name='conductiviteFlamme',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='charge_surfacique_de_la_végétation',
            new_name='deltat',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='coefficient_absorption_combustible',
            new_name='deltax',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='conductivite_de_la_flamme',
            new_name='deltay',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='conductivite_des_braises',
            new_name='directionDuVen',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='coordonnées_x_depart_de_feu',
            new_name='emissiviteBraise',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='coordonnées_y_depart_de_feu',
            new_name='longueurEclosion',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='densite_de_la_végétation',
            new_name='nbEclosion',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='diametre_du_combustible',
            new_name='pentex',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='direction_du_vent',
            new_name='pentey',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='emissivite_des_braises',
            new_name='temperatureAir',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='emissivite_du_combustible',
            new_name='temperatureAllumage',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='hauteur_de_la_végétation',
            new_name='temperatureBrais',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='limite_finale_ox',
            new_name='temperatureFlamme',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='limite_finale_oy',
            new_name='timeAllumage',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='limite_initiale_ox',
            new_name='timeMax',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='limite_initiale_oy',
            new_name='timp',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='longueur_de_la_flamme',
            new_name='typeVegetation',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='longueur_du_depart_de_feu',
            new_name='viscositeAirChau',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='ordonnée_du_point_d_enregistrement',
            new_name='vitesseDuVent',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='pas_d_espace_ox',
            new_name='xDebut',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='pas_d_espace_oy',
            new_name='xEclosion',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='pas_de_temps',
            new_name='xFin',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='pente_suivant_ox',
            new_name='xenreg',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='pente_suivant_oy',
            new_name='yDebut',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='temperature_ambiante',
            new_name='yEclosion',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='temperature_d_allumage',
            new_name='yFin',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='temperature_de_la_flamme',
            new_name='yenr',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='cote_du_site_en_feu',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='temperature_des_braises',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='temps_d_allumage',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='temps_de_combustion',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='temps_de_simulation',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='teneur_en_eau_de_la_végétation',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='viscosité_de_l_aire_chaud',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='vitesse_du_vent',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='x_zone_de_calcul_final',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='x_zone_de_calcul_initial',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='y_zone_de_calcul_final',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='y_zone_de_calcul_initial',
        ),
        migrations.AddField(
            model_name='simulation',
            name='nbreVegetation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='region',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='ville',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simulation',
            name='absorptionFuelBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.absorptionfuelbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='chaleurSpecFeulBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.chaleurspecfeulbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='chargeSurface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.chargesurface'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='densiteFuelBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.densitefuelbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='diametreFuelBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.diametrefuelbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='emissiviteFuelBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.emissivitefuelbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='hauteurFlamme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.hauteurflamme'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='hauteurFuelBed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.hauteurfuelbed'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='teneurEnEau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.teneureneau'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='timeCombustion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.timecombustion'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='x1veg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.x1veg'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='x2veg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.x2veg'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='y1veg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.y1veg'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='y2veg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.y2veg'),
        ),
    ]
