# Generated by Django 4.2.5 on 2023-10-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0011_absorptionfuelbed_chaleurspecfeulbed_chargesurface_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimiteInitialOX',
        ),
        migrations.RenameField(
            model_name='simulation',
            old_name='yenr',
            new_name='yenreg',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='nbEclosion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='typeVegetation',
            field=models.IntegerField(default=0),
        ),
    ]
