# Generated by Django 4.2.5 on 2023-10-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0013_rename_chaleur_spec_fuel_bed_chaleurspecfeulbed_chaleur_spec_feul_bed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absorptionfuelbed',
            options={'verbose_name': 'AbsorptionFuelBed', 'verbose_name_plural': 'AbsorptionFuelBeds'},
        ),
        migrations.AlterModelOptions(
            name='chaleurspecfeulbed',
            options={'verbose_name': 'ChaleurSpecFeulBed', 'verbose_name_plural': 'ChaleurSpecFeulBeds'},
        ),
        migrations.AlterModelOptions(
            name='chargesurface',
            options={'verbose_name': 'ChargeSurface', 'verbose_name_plural': 'ChargeSurfaces'},
        ),
        migrations.AlterModelOptions(
            name='densitefuelbed',
            options={'verbose_name': 'DensiteFuelBed', 'verbose_name_plural': 'DensiteFuelBeds'},
        ),
        migrations.AlterModelOptions(
            name='diametrefuelbed',
            options={'verbose_name': 'DiametreFuelBed', 'verbose_name_plural': 'DiametreFuelBeds'},
        ),
        migrations.AlterModelOptions(
            name='emissivitefuelbed',
            options={'verbose_name': 'EmissiviteFuelBed', 'verbose_name_plural': 'EmissiviteFuelBeds'},
        ),
        migrations.AlterModelOptions(
            name='fractionvolumiq',
            options={'verbose_name': 'FractionVolumiq', 'verbose_name_plural': 'FractionVolumiqs'},
        ),
        migrations.AlterModelOptions(
            name='hauteurflamme',
            options={'verbose_name': 'HauteurFlamme', 'verbose_name_plural': 'HauteurFlammes'},
        ),
        migrations.AlterModelOptions(
            name='hauteurfuelbed',
            options={'verbose_name': 'HauteurFuelBed', 'verbose_name_plural': 'HauteurFuelBeds'},
        ),
        migrations.AlterModelOptions(
            name='surfacespec',
            options={'verbose_name': 'SurfaceSpec', 'verbose_name_plural': 'SurfaceSpecs'},
        ),
        migrations.AlterModelOptions(
            name='teneureneau',
            options={'verbose_name': 'TeneurEnEau', 'verbose_name_plural': 'TeneurEnEaus'},
        ),
        migrations.AlterModelOptions(
            name='timecombustion',
            options={'verbose_name': 'TimeCombustion', 'verbose_name_plural': 'TimeCombustions'},
        ),
        migrations.AlterModelOptions(
            name='x1veg',
            options={'verbose_name': 'X1veg', 'verbose_name_plural': 'X1vegs'},
        ),
        migrations.AlterModelOptions(
            name='x2veg',
            options={'verbose_name': 'X2veg', 'verbose_name_plural': 'X2vegs'},
        ),
        migrations.AlterModelOptions(
            name='y1veg',
            options={'verbose_name': 'Y1veg', 'verbose_name_plural': 'Y1vegs'},
        ),
        migrations.AlterModelOptions(
            name='y2veg',
            options={'verbose_name': 'Y2veg', 'verbose_name_plural': 'Y2vegs'},
        ),
        migrations.AlterModelTable(
            name='absorptionfuelbed',
            table='AbsorptionFuelBed',
        ),
        migrations.AlterModelTable(
            name='chaleurspecfeulbed',
            table='ChaleurSpecFeulBed',
        ),
        migrations.AlterModelTable(
            name='chargesurface',
            table='ChargeSurface',
        ),
        migrations.AlterModelTable(
            name='densitefuelbed',
            table='DensiteFuelBed',
        ),
        migrations.AlterModelTable(
            name='diametrefuelbed',
            table='DiametreFuelBed',
        ),
        migrations.AlterModelTable(
            name='emissivitefuelbed',
            table='EmissiviteFuelBed',
        ),
        migrations.AlterModelTable(
            name='fractionvolumiq',
            table='FractionVolumiq',
        ),
        migrations.AlterModelTable(
            name='hauteurflamme',
            table='HauteurFlamme',
        ),
        migrations.AlterModelTable(
            name='hauteurfuelbed',
            table='HauteurFuelBed',
        ),
        migrations.AlterModelTable(
            name='surfacespec',
            table='SurfaceSpec',
        ),
        migrations.AlterModelTable(
            name='teneureneau',
            table='TeneurEnEau',
        ),
        migrations.AlterModelTable(
            name='timecombustion',
            table='TimeCombustion',
        ),
        migrations.AlterModelTable(
            name='x1veg',
            table='X1veg',
        ),
        migrations.AlterModelTable(
            name='x2veg',
            table='X2veg',
        ),
        migrations.AlterModelTable(
            name='y1veg',
            table='Y1veg',
        ),
        migrations.AlterModelTable(
            name='y2veg',
            table='Y2veg',
        ),
    ]
