# Generated by Django 4.2.5 on 2023-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0014_alter_absorptionfuelbed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='absorptionFuelBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='chaleurSpecFeulBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='chargeSurface',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='densiteFuelBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='diametreFuelBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='emissiviteFuelBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hauteurFlamme',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hauteurFuelBed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='teneurEnEau',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='timeCombustion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='x1veg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='x2veg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='y1veg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='y2veg',
            field=models.FloatField(default=0.0),
        ),
    ]
