# Generated by Django 4.2.5 on 2023-10-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0015_alter_simulation_absorptionfuelbed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='coteSiteFeu',
            field=models.CharField(default='', max_length=10),
        ),
    ]
